### PR TITLE
pyproject.toml: Unpin `packaging` now that `pip-requirements-parser` pins it

### LINKED ISSUE #426: Incompatibility with packaging>=22.0: cannot import name 'LegacyVersion' from 'packaging.version'
## Bug description

pip-audit is incompatible with latest version of `packaging`, due to [removed `LegacyVersion` ](https://github.com/pypa/packaging/blob/main/CHANGELOG.rst#220---2022-12-07)

## Reproduction steps

1. `pip install  pip-audit`
2. Check that `packaging` version is >= 22.0
3. Run `pip freeze | pip-audit --no-deps -r -` to check the currently installed packages

## Expected behavior

`pip-audit` installs a compatible version of `packaging`

## Screenshots and logs

```
Traceback (most recent call last):
  File "/usr/local/bin/pip-audit", line 5, in <module>
    from pip_audit._cli import audit
  File "/usr/local/lib/python3.9/site-packages/pip_audit/_cli.py", line 17, in <module>
    from pip_audit._audit import AuditOptions, Auditor
  File "/usr/local/lib/python3.9/site-packages/pip_audit/_audit.py", line 10, in <module>
    from pip_audit._dependency_source import DependencySource
  File "/usr/local/lib/python3.9/site-packages/pip_audit/_dependency_source/__init__.py", line 14, in <module>
    from .requirement import RequirementSource
  File "/usr/local/lib/python3.9/site-packages/pip_audit/_dependency_source/requirement.py", line 19, in <module>
    from pip_requirements_parser import InstallRequirement, InvalidRequirementLine, RequirementsFile
  File "/usr/local/lib/python3.9/site-packages/pip_requirements_parser.py", line 73, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/usr/local/lib/python3.9/site-packages/packaging/version.py)
```

## Platform information

* OS name and version: docker, python:3.9-alpine
* `pip-audit` version (`pip-audit -V`): 2.4.7
* Python version (`python -V` or `python3 -V`): 3.9.15
* `pip` version (`pip -V` or `pip3 -V`): 22.0.4

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
Closes #426

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
`pip-requirements-parser` just shipped `32.0` before which pins `packaging`. They have a more comprehensive fix in the works which involves vendoring `LegacyVersion`.

Anyway, I think we can just unpin this for now.

**Comment by di** [comment]
We should increase the lower bound on `pip-requirments-parser` as well to make sure the new version is being resolved.

**Review by di — APPROVED** [review]

**Comment by ringohoffman** [comment]
Any chance a release can be generated including this PR?

**Comment by woodruffw** [comment]
@ringohoffman Are you seeing errors with the latest release? 2.4.8 includes https://github.com/pypa/pip-audit/pull/427, which pins `packaging` so that `pip-requirements-parser` doesn't fetch a newer one.

**Comment by ringohoffman** [comment]
My mistake, I misinterpreted this PR. I'll be keeping an eye on https://github.com/nexB/pip-requirements-parser/issues/10

**Pull request merged**
